apiVersion: apps/v1
kind: Deployment
metadata:
  name: enowshop-frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: enowshop-frontend
  template:
    metadata:
      labels:
        app: enowshop-frontend
    spec:
      containers:
        - name: enowshop-frontend
          image: gcr.io/enowhop/enowshop-frotend:latest
          ports:
              - containerPort: 3000
          env:
            - name: A_VUE_APP_BASE_BACKEND_URL
              value: http://35.245.229.86.nip.io
            - name: A_VUE_APP_BASE_BACKEND_URL_USER
              value: http://35.245.229.86.nip.io/user
            - name: A_VUE_APP_BASE_BACKEND_URL_PRODUCTS
              value: http://35.245.229.86.nip.io/invetory
            - name: A_VUE_APP_BASE_BACKEND_URL_ADM
              value: http://35.245.229.86.nip.io/admin
            